font_family               Fira Code Nerd Font Medium
font_size                 10.0
tab_bar_edge              top
tab_bar_style             powerline
tab_powerline_style       round
cursor_shape              beam
default_pointer_shape     arrow
open_url_modifiers        ctrl
background_opacity        0.95
background                #181818
foreground                #dfdfdf
cursor                    #ffffff
selection_background      #dfdfdf
color0                    #474747
color8                    #474747
color1                    #f44336
color9                    #f44336
color2                    #4caf50
color10                   #4caf50
color3                    #ff9800
color11                   #ff9800
color4                    #1a73e8
color12                   #1a73e8
color5                    #9c27b0
color13                   #9c27b0
color6                    #0097a7
color14                   #0097a7
color7                    #ffffff
color15                   #ffffff
selection_foreground      #181818
window_padding_width      4
map ctrl+c                copy_and_clear_or_interrupt
map ctrl+v                paste_from_clipboard
map ctrl+с                copy_and_clear_or_interrupt
map ctrl+м                paste_from_clipboard
term                      xterm-256color
update_check_interval     0
active_tab_foreground     #ffffff
active_tab_background     #1a73e8
inactive_tab_foreground   #474747
inactive_tab_background   #ffffff
active_tab_font_style     normal
editor                    nvim
focus_follows_mouse       yes