font:
  normal:
    family: 'Cascadia Code'
    style: Regular
  bold:
    family: 'Cascadia Code'
    style: Bold
  italic:
    family: 'Cascadia Code'
    style: Italic
  bold_italic:
    family: 'Cascadia Code'
    style: Bold Italic
  offset:
    x: 0
    y: 0
window:
  decorations: none
colors:
  primary:
    background: '0x1E1E1E'
    foreground: '0xFFFFFF'
  normal:
    black: '0x241F31'
    red: '0xC01C28'
    green: '0x2EC27E'
    yellow: '0xF5C211'
    blue: '0x1E78E4'
    magenta: '0x9841BB'
    cyan: '0x0AB9DC'
    white: '0xC0BFBC'
  bright:
    black: '0x5E5C64'
    red: '0xED333B'
    green: '0x57E389'
    yellow: '0xF8E45C'
    blue: '0x51A1FF'
    magenta: '0xC061CB'
    cyan: '0x4FD2FD'
    white: '0xF6F5F4'
